name: Build Publish
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Configurar jdk
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Executa testes com Maven
        run: mvn test

      - name: Empacota artefato com Maven
        run: mvn package -DskipTests

      - name: Faz o upload do artefato
        uses: actions/upload-artifact@v7
        with:
          name: api-market-place-artifact
          path: application/target

  publish_to_registry:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Download do artefato
        uses: actions/download-artifact@v8
        with:
          name: api-market-place-artifact
          path: application/target

      - name: Login em Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extrai metadata (tags, labels) do docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: avparaujo/api-market-place

      - name: Constrói e envia imagem docker
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Gera atestado da imagem
        uses: actions/attest@v4
        id: attest
        with:
          subject-name: index.docker.io/avparaujo/api-market-place
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  integration_tests:
    needs: [publish_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Configurar jdk
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Executa testes de integração com Maven
        run: mvn test -DintegrationTests
